apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-task
spec:
  storageClassName: "stclass-task"
  capacity:
    storage: 20Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/my-pv"